version: '3.7'
services:
  mysql:
    container_name: ${APP_NAME}_mysql
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
      args:
        - VERSION=${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./docker/mysql/storage:/var/lib/mysql
      - ./docker/mysql/utf8.cnf:/etc/mysql/conf.d/utf8.cnf
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  redis:
    container_name: ${APP_NAME}_redis
    image: redis:${REDIS_VERSION}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./docker/redis/storage:/data
  php:
    container_name: ${APP_NAME}_php
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      args:
        - APP_NAME=${APP_NAME}
        - VERSION=${PHP_VERSION}
        - XDEBUG=${XDEBUG}
    volumes:
      - ./src/:/var/www/${APP_NAME}/
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_CLIENT_PORT=${XDEBUG_PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
      - redis
  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:${NGINX_VERSION}
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./src/:/var/www/${APP_NAME}/
      - ./docker/nginx/default.template:/etc/nginx/conf.d/default.template
    environment:
      - APP_NAME=${APP_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: /bin/bash -c "envsubst '$$APP_NAME' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php
