#!/bin/sh

if [ -f ../../src/tools/php-cs-fixer/vendor/bin/php-cs-fixer ]
then
    ../../src/tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --diff -v --rules=@PSR12 ../../src/src

    if [ $? -ne 0 ]
    then
        RED='\033[0;31m'
        CYAN='\033[0;36m'
        NA='\033[0m'

        printf "\n\t${CYAN}[GIT POLICY]${NA} PHP-CS-Fixer has failed - ${RED}Push Aborted${NA}\n\n"

        return 1
    fi
fi
